### ISSUE TITLE
Update ReadMe to comment on relative performance difference between C# and C++

### ISSUE THREAD

**Issue by kasajian** [Microsoft/FASTER#1]
It would be useful to have some comments about the relative performance difference between the two.

1.  For instance, is C# simply a wrapper around the C++ version?
2.  Does C++ benefit somehow by using memory-mapped files, using blt'able types to write structures directly to disk, which may not be feasible in C#.   Or if such techniques are used, are C# Spans being used?  Alternatively, if the underlying architecture is relatively neutral with no real significant difference between C++ and C# that would also be valuable to know.

**Comment by jahunter-m** [comment]
Good suggestion, thanks. Performance between C++ and C# versions is effectively the same. So far, we have not discovered a technique that works in C++ that we have not been able to implement in C#.

**Comment by jahunter-m** [comment]
We should add that to the README, as you suggest.

**Comment by kasajian** [comment]
That's actually very useful to know -- thanks for the prompt feedback.

**Comment by dzmitry-lahoda** [comment]
Could it be possible to eliminate C++ code?

1. https://github.com/Microsoft/FASTER/blob/master/cs/src/native/adv-file-ops/adv-file-ops.cpp

https://twitter.com/xoofx/status/1031645672821469187


2.  https://github.com/Microsoft/FASTER/blob/master/cs/src/native/readtsc/readtsc.cpp

I guess need to create issue request for 

https://github.com/dotnet/corefx/tree/master/src/Common/src/CoreLib/System/Runtime/Intrinsics/X86

**Comment by badrishc** [comment]
Good points, yes adv-file-ops may be possible to eliminate. We actually need to convert the IDevice implementation (the main user of adv-file-ops) to be platform agnostic without losing perf when on Windows, i.e., continue to use the native Windows API as we do currently, in that setting. Would be nice to see a pull request for this.

As for, readtsc, actually it is not required in core at all: it was used only for latency testing because Stopwatch was too slow when measuring latency of individual ops. I will move readtsc to benchmark/eliminate it entirely.

**Comment by badrishc** [comment]
Updated README, closing.

**Comment by vibeeshan025** [comment]
Is it true to mac OS as well, When i run the provided sample project in mac, everything is working except (at least there is no any exception), i didn't see any file on the disk.
