### ISSUE TITLE
Stuck in check point for 12 hours

### ISSUE THREAD

**Issue by somecoder2019** [Microsoft/FASTER#102]
Hi,

I am doing a large graph computation using multiple threads. I create two fht's, one for storing and other for indexing. All the threads use a singleton class to interact with the store. The singleton class exposes methods to create, RMW, read etc. The singleton class spawns off a thread that takes a snapshot of the two FasterKV's I am using. All the methods in the class wait for the checkpoint to finish. So, if there is a checkpoint going on and a thread calls one of the methods in the class, it will wait because the first two lines of every method is:

```
            fht1.CompleteCheckpoint(true);
            fht2.CompleteCheckpoint(true);
```

Each object stored is almost 1KB in size. I am printing entry count when we start snapshot. As you can see it is fairly large (this is after 15 minutes of computation). Is this the reason why the program is stuck for 12 hours, all threads waiting for computation to finish?

```

            73849447-4c68-4dd1-bc87-d145174401fb
            fht1 Snapshot started: 1282531
            fht2 Snapshot started: 70292

```

To add, I checked the snapshot folder and there is a 100KB file created with the name _snapshot.dat.obj.log_ It was in this state for a lot of time without being updated.

**Comment by badrishc** [comment]
You do not really need to wait for checkpoints to complete before issuing operations. FASTER can handle requests while checkpointing is going on. All you need to ensure is that NEW threads don't register themselves with FASTER while checkpointing is actively occurrining.

That said, I cannot think of a reason why the snapshot should take so long. You might try disabling one of the two instances to see if that helps. Is it possible to create a simple stand alone repro that demonstrates the problem? Also adding @gunaprsd for providing other suggestions.

**Comment by badrishc** [comment]
Also, you need to make sure no thread is sleeping or doing stuff without periodically refreshing by calling fht.Refresh().

**Comment by somecoder2019** [comment]
Thanks @badrishc 

I have created the below gist that is not exactly using the same object as I out int he store. But I am using the same thread access pattern. I modified the example in the documentation. The issue repro's. It is taking checkpoint and never finishes.

https://gist.github.com/somecoder2019/a99cb4721fb9444ac272ace8af017ee0

**Comment by badrishc** [comment]
First of all, thanks for the simple and excellent repro!

The problem is that you are not periodically calling refresh from session threads. Refresh is the mechanism threads use to report forward progress to the system. If you change the inner loop, in both RunSession() and ContinueSession(), to the below, it will work:

```c#
 if (seq % 1024 == 0)
{
    fht.Refresh();

    if (seq % 65536 == 0)
    {
        fht.CompletePending(false);
    }
}
```

A couple other side notes:

(1) As a heads up, you may need to use a better 64-bit hash/comparer for keys in future if you run into performance issues:

```c#
public struct LongComparer : IFasterEqualityComparer<long>
{
    public bool Equals(ref long k1, ref long k2) => k1 == k2;
    public long GetHashCode64(ref long k) => Utility.GetHashCode(k);
}

fht = new FasterKV<long, long, long, long, Empty, Funcs>
            (..., comparer: new LongComparer());
```

(2) You can kill your program, change Run() to Continue() and perform recovery. However, the local variable `fullCheckpointToken` will be lost on recovery. You can either choose a particular recovery token from storage, or simply ask FASTER to use the latest recovery token as follows:

```c#
fht.Recover();
```

I ran the recovery code path and verified that it works as well, and resumes session 1 at a particular offset.

**Comment by somecoder2019** [comment]
Thanks @badrishc. That solved the issue for me.

I am hitting a different issue with serialization and deserialization but will open a separate issue.

**Comment by badrishc** [comment]
You might also try the "readcache" branch, that has some bugfixes related to serialization.

**Comment by somecoder2019** [comment]
Will do. Thanks.
