### ISSUE TITLE
What happens to class objects when in-memory limit exceeded?

### ISSUE THREAD

**Issue by matthewbrookes** [Microsoft/FASTER#113]
Hi, I have a question related to memory allocation/deallocation when using FASTER with a Value class that stores a byte array (i.e uint8_t*):

What happens to the memory allocated to the byte array when the value is moved from the in-memory portion to on-disk portion of HybridLog?

I've created a `sum_store` style example which populates the store with Values containing byte arrays however when running it through `valgrind` I see huge amounts of memory leakage. Is this because the memory backing the array is not being freed? I'm quite confused as to what happens to values when spilling to disk. I'd be very grateful for some guidance as to what happens here. The C++ examples use primitive types (which I guess are trivial to move to disk) but I want to be able to story arbitrary length byte arrays in FASTER.

**Comment by badrishc** [comment]
FASTER C# and C++ are slightly different in their handling of variable length types. Because class objects in C# are stored on the heap with automatic GC provided by the runtime, FASTER C# supports a separate object log where items are serialized when the log is flushed to storage.

In C++, in keeping with jemalloc-style object allocation, variable length values are allocated directly on the hybrid log in-place. See our [wiki post](https://github.com/Microsoft/FASTER/wiki/Variable-length-values#in-c) for more details on this, and how to allocate variable length arrays directly on the hybrid log.

**Comment by matthewbrookes** [comment]
Thanks for pointing me to the wiki post. I guess what I'm wondering is, if I have a Value class that contains a pointer to some heap allocated memory, when that Value gets moved to the On-Disk portion will it just be the pointer that is copied and FASTER is unaware of the contents being pointed to? Thus presumably the data (on the heap) is not actually being stored in FASTER.

**Comment by badrishc** [comment]
You are correct.

**Comment by matthewbrookes** [comment]
Great, thanks for confirming that. I think my understanding of FASTER is improving, but don't be too surprised if I come back with more questions ;)

**Comment by matthewbrookes** [comment]
Hi, sorry to reopen this. Having looked at the following [test](https://github.com/Microsoft/FASTER/blob/3ad0a96b67f388f2e7726396c0f07d06223facd6/cc/test/in_memory_test.cc#L596) I think it is implementing roughly what I'm looking for. I'm wondering though what happens when the value is moved to the disk? Is the `buffer()` method returning something that is heap allocated or will the data be moved onto the log with the Value?

**Comment by badrishc** [comment]
The example you pointed to shows how variable sized objects are allocated in the log. You can see that the log stores the value of the buffer _in place_, in the space allocated for the value on the log itself. In other words, the log is also serving as your memory allocator (instead of malloc). Hope that makes sense.

```c++
    inline const uint8_t* buffer() const {
      return reinterpret_cast<const uint8_t*>(this + 1);
    }
    inline uint8_t* buffer() {
      return reinterpret_cast<uint8_t*>(this + 1);
    }
```

The Put operations defined in UpsertContext as responsible for deep-copying your value into the log at the time of Upsert into FASTER:

```c++
    inline void Put(Value& value) {
      value.gen_lock_.store(0);
      value.size_ = sizeof(Value) + length_;
      value.length_ = length_;
      std::memset(value.buffer(), 88, length_);
    }
    inline bool PutAtomic(Value& value) {
      bool replaced;
      while(!value.gen_lock_.try_lock(replaced) && !replaced) {
        std::this_thread::yield();
      }
      if(replaced) {
        // Some other thread replaced this record.
        return false;
      }
      if(value.size_ < sizeof(Value) + length_) {
        // Current value is too small for in-place update.
        value.gen_lock_.unlock(true);
        return false;
      }
      // In-place update overwrites length and buffer, but not size.
      value.length_ = length_;
      std::memset(value.buffer(), 88, length_);
      value.gen_lock_.unlock(false);
      return true;
    }
```

When the value is moved to disk, since it was allocated directly in place in the log, the value will also move to disk along with the key.

**Comment by matthewbrookes** [comment]
Hey, thanks for the detailed explanation of what's going on. I understand now from a high-level perspective how the allocation on the log is working. The one aspect I'm fuzzy on (because I'm not really a C++ developer) is how this `buffer()` method is working. From my reading of docs on `reinterpret_cast` I understand that it's changing the pointer to `(this + 1)` into a `uint8_t*` but what's the purpose of the `+ 1`?

**Comment by badrishc** [comment]
We allocate enough space on the log for both the value header (which consists of AtomicGenLock gen_lock_, uint32_t size_, and uint32_t length_) and the actual buffer data itself. An easy way to move the pointer to the actual data is to use (this + 1), because the size of "this" is the total header itself, and pointer arithmetic adds in steps of the static object size. Thus, (this + 1) points to the address immediately after the above-mentioned value header, which is where the buffer data would reside. We then simply cast it to our intended variable-length value type.

Note here that in the header, size_ refers to the max size that the buffer can take, and length_ refers to the actual length used by the buffer right now. This is only so that we may resize the buffer in-place, up to length_, without having to re-allocate a larger buffer on the tail of the log.

**Comment by matthewbrookes** [comment]
Perfect thanks for such a helpful explanation :smile:
