### ISSUE TITLE
"Overflow in AddressInfo" when using variable length non-blittable types

### ISSUE THREAD

**Issue by marius-klimantavicius** [microsoft/FASTER#152]
From what I see current implementation only support variable length key/values if and only if both key and value are blittable types. For my scenario I'd like to have string/byte[] as keys and byte[] (or even a custom object I could (de)serialize during Read/Write) values. 
I could follow the variable length example to implement a struct which would contain string/byte[] data. One issue with that approach is that I'd need to do additional copy from string/byte[] to allocated memory block (and back but this is expected), for it to be simply copied by FASTER to its own buffers (though as I understand this still happens when using custom serializer for cases when key/value has objects). Another issue - pointer/managed ref lifetime, when can I release (or unpin) the memory, is it safe to do just after Upsert/Delete/Read? When implementing IFunctions - do I need to pin src/dst?

**Comment by marius-klimantavicius** [comment]
For now I opted to go with wrapping variable length structs with custom serializers (https://github.com/marius-klimantavicius/mister).

**Comment by badrishc** [comment]
There are two ways to support variable length values, as you have noticed. One is to just treat the key and values as class objects and use FASTER's support of objects via a custom serializer. This is the safe technique, but may incur overhead when reading objects that need to be fetched from storage. This is because the objects are stored in a separate object log, with the main log storing pointers to the object log. Thus, a read would first go to the main log, determine the offset in object log, and issue another IO to fetch the object.

The other technique is to store variable length objects in place in the main hybrid log. This is illustrated in the example [here](https://github.com/microsoft/FASTER/tree/master/cs/playground/VarLenStructSample).

You are right that you would need to copy the bytes over from/to this struct during the operation, and FASTER would then copy it to its own log later. The pointer lifetime is not as hard as you might think though. You just need to keep it pinned (or use stackalloc) until Upsert/Read returns. When it returns, you can safely unpin. This is because if the operation goes pending, then FASTER will deep-copy the data to its internal pending context [here](https://github.com/microsoft/FASTER/blob/506b1bfb69daf1ebdc12704788b1dc8d34784433/cs/src/core/Index/Common/HeapContainer.cs#L59) before returning to the caller.

The "variable length struct" feature is rather low-level -- it is possible to build a layer on top that can directly support byte-arrays or MemorySpan<T> for users. This is an open enhancement.

If you have ideas on better support for such types, feel free to suggest.

**Comment by marius-klimantavicius** [comment]
For my project I ended up going with variable length struct. When I started working on my project I tried using the object log, but it was failing for me. I was witnessing `"Overflow in AddressInfo"` when trying to insert ~4M entries to FKV where key was `i.ToString()` and value was byte array of length 7. I was also experiencing memory corruptions randomly when working with smaller number of entries (mostly during recovery in form of `FatalEngineException` caused by access violation).
Initially I thought that the issue was that object log did not support variable length non-blittable types, but now looking into code it seems to be something else.

**Comment by badrishc** [comment]
Do you have a repro for the 'overflow in addressinfo' issue? This sounds like a bug that needs to be fixed.

You need to do compete pending, but not immediately. You can do it after some number of operations. That said, upserts almost never go pending (only in special case when taking checkpoint and also using RMW) so it doesn't matter in your case.

**Comment by marius-klimantavicius** [comment]
Created a gist (https://gist.github.com/marius-klimantavicius/370a42e3ae698dc17959994908ff33c3) for this case - need to take checkpoint to reproduce the issue.

**Comment by badrishc** [comment]
I ran this sample in net46 Debug and net46 Release, both attached and detached to debugger, several times, on Windows. No error. Can you clarify your environment/OS and what platform/config you are hitting the error on? I used the latest in master. Thanks!

**Comment by badrishc** [comment]
Ah, I see the error occurs in 32 bit mode. This is expected, as the addressable space is much lower in 32 bit as compared to 64 bit. We only have 32 bits to store AddressInfo, so we do not have much budget in terms of bits to store large offsets within a page there.

I recommend you run your program in 64 bit mode (right click project, choose platform target as x64). We will update the error message to make this situation clearer. Thanks, and let me know if you still hit the issue. :)

**Comment by marius-klimantavicius** [comment]
I can confirm that I cannot reproduce the issue with 64-bit target.
This is not an issue for me as I switched to using variable length structs strategy to work this one around.

If there are no plans to support large number of non-blittable key/value in 32-bit environment, then this issue can be closed. It is really easy to fall into this trap as VS generates "Prefer 32 bit" by default for new projects.

**Comment by badrishc** [comment]
This isn't easy to fix with the current design of FASTER, where the pointer is used to store object log offset and object size. We have updated the error message to suggest moving to x64.
