### ISSUE TITLE
Lost entries after FlushAndEvict

### ISSUE THREAD

**Issue by marius-klimantavicius** [microsoft/FASTER#165]
Steps to reproduce (I am using variable length struct):
1. Upsert a few key/values
1. Call FlushAndEvict(true)
1. Take a FoldOver snapshot
1. Restart application
1. Upsert another key/value (I was using different from others)
1. Take a FoldOver snaphot
1. Restart application

Expected result?:
Upserted values in step (1) are still available

Actual result:
Only key/value upserted in step (5) is available (this can also be verified by looking into hlog with hex editor - all(most all) bytes expect for the last key/value is `0`).

This is not consistent - it happens most of the time when I am testing, but not always. I am using my wrapper (thus I am not yet providing gist to reproduce the issue, I'll need to extract the minimum required parts) so it is possible that I am using FASTER incorrectly.

**Comment by marius-klimantavicius** [comment]
I think that change in the condition would fix this one:
```C#
// Special case: we do not load any records into memory
if (headAddress == untilAddress)
{
  hlog.AllocatePage(hlog.GetPageIndexForAddress(headAddress));
}
```

Change condition to `headAddress == untilAddress && headAddress == Constants.kFirstValidAddress` ? This way we load a page from disk except when the log is empty. This is needed because flush operates at page level and if the page is not loaded then we lose existing data when trying to flush again.

**Comment by badrishc** [comment]
Excellent catch! Your fix looks fine.

This is a regression introduced by a recent effort to reduce the number of I/Os performed during recovery, if head address were at tail at the time of the checkpoint. If we want to avoid read IO during recovery in this situation, we would need to fix the page flush so that it flushes partially (from headAddress to page end). This strategy is however complicated by the fact that page flushes occur at 512 byte granularity, which means we may need to read back some bytes before the flush.

**Comment by badrishc** [comment]
See PR https://github.com/microsoft/FASTER/pull/168 for both this issue and adding begin address to recovery info.
