### ISSUE TITLE
How to use Faster as Pure in memory KV store

### ISSUE THREAD

**Issue by ajaybodhe** [microsoft/FASTER#194]
Hello,
I looked at some sample examples of Faster and we need to provide LogSettings for creative it.
Can we run Faster as pure in memory caching layer as substitute to ConcurrentDictionary without providing LogSettings ?
I am not clear why the logs file is essentially being used for?

Thanks,
Ajay

**Comment by badrishc** [comment]
Logs are used so that larger-than-memory data can be referenced and indexed by the store. You can run FASTER in pure in-memory mode by using `NullDevice` as the log device. You can use `faster.Log.ShiftBeginAddress(faster.Log.HeadAddress)` to set the log beginning address to the head address, so that the system never goes to disk.
