### ISSUE TITLE
[Question] how does FASTER handle logic address running out?

### ISSUE THREAD

**Issue by sillyousu** [microsoft/FASTER#20]

**Comment by badrishc** [comment]
Short answer: it doesn't, right now. We plan to support address wraparound in the future (it mainly involves simple adjustments to the address comparison checks in the code). The logical address should not run out in practice for a long time, since logs grow much slower in FASTER compared to pure log-structured systems. A possible alternate workaround to handle addresses running out is to take a checkpoint, and recover to a compacted version of the log. This isn't yet implemented out of the box either.

**Comment by badrishc** [comment]
We have implemented draft support for address rollover beyond 48 bits (`Constants.kAddressMask`) by using a custom comparison operator that performs arithmetic with rollover.

This allows addresses to grow beyond 48 bits (up to 64 bits), as long as the active portion of the log is no larger than half the valid (48 bit) address space. Address cleanup logic has been made more frequent (every quarter of the address space) to ensure this property as well. We simply let offsets such as `HeadAddress` and tail address grow beyond 48 bits in this implementation. It is possible to extend the logic to support true rollover beyond 64 bits, but we do not see a reason for this extension at this point.

Since the change adds additional complexity in critical sections of the code, we will not be merging this into master unless we see a concrete use case for it. We have found 48 bits of address space to be sufficient for all applications until now. Further, one may easily increase the actual address space from 48 up to 62 bits simply by reducing the tag size. The support for larger address spaces is present at https://github.com/microsoft/FASTER/tree/addr-rollover.
