### ISSUE TITLE
Log and objLog always have size of 1gb

### ISSUE THREAD

**Issue by dangershony** [microsoft/FASTER#224]
Hi, when I create the logs and take a checkpoint I notice the log size is `1.00 GB (1,073,741,824 bytes)`
No matter if I delete or add more entries, is that intentional and is there a way to control the size (and shrink it when deletes occur)

Note changing the `FasterKV(long size,..` param doesn't change the file size.

**Comment by badrishc** [comment]
The file on disk is broken into segments, each of size governed by segment size, see here: https://microsoft.github.io/FASTER/tuning/Log.html

For efficiency, the entire segment is preallocated by default. To instead allocate only what's used, set preallocateFile to false during CreateLogDevice.

The segments will get deleted as you truncate from the head of the log, e.g. by performing log compaction. Examples in playground illustrate this.

**Comment by dangershony** [comment]
Thank for the respons, is there a significant degradance in performance if not pre allocating?
If I know in advance to total size of the data set can I set that and effect the size on disk?

**Comment by badrishc** [comment]
There shouldn't be significant degradation for typical workloads, particularly those involving object log. The total size of dataset can roughly guide the size of a segment, but it's more importantly related to the granularity at which we delete from the head of the log during compaction or log truncation.

**Comment by dangershony** [comment]
Thanks I'll give it a go and of it solved my issue I will close the PR

**Comment by dangershony** [comment]
I noticed the log files are only created when calling the `FasterKV.Recover()` method, is that correct?

What is the best recommended approach to persistence points? on startup should I call recover to create logs? or just relay on checkpoint is enough?

Also I assume old checkpoints can be deleted.

**Comment by badrishc** [comment]
Are you taking snapshot or fold-over checkpoints (see [here](https://github.com/Microsoft/FASTER/blob/master/cs/README.md#checkpointing-and-recovery))? With snapshot checkpoints, the main log will not get written to disk during the checkpoint because the entire in-memory snapshot is stored in a separate file.

Generally, you take periodic checkpoints of FasterKv during normal operation. Then, after failure, you recover from any previously completed checkpoint, that's pretty much it. You don't have to worry about explicitly persisting logs, it will be taken care of during checkpointing.

**Comment by dangershony** [comment]
For now my issues are solved so closing thanks for the help.

**Comment by badrishc** [comment]
Great, let us know the results of your investigations wrt viability for using FASTER in your scenario, and if you have any comments for improvement.
