### ISSUE TITLE
[C#] Entries Cant Be Recovered After Process Restart

### ISSUE THREAD

**Issue by ThiagoT1** [microsoft/FASTER#225]
Hello!!

It seems https://github.com/microsoft/FASTER/issues/216 might not be fixed.

Please take a look at https://github.com/ThiagoT1/FasterDictionary/tree/help-1.0.0

Four tests were built to expose the exact threshold where the recover becomes impossible, either with Snapshot or FoldOver checkpoint types.

https://github.com/ThiagoT1/FasterDictionary/blob/bf21f2bab984a382e1000d04aef92db0f5440c2b/tests/FasterDictionary.Tests/Recover/RecoverTests.cs#L37

![image](https://user-images.githubusercontent.com/16569217/71749853-5fa57c00-2e55-11ea-88ac-45ec8980a1af.png)

Please note that while serializers are being used, all values are fixed length, albeit implicitly.

Blittable types were ignored on purpose and a strategy for int serializing was placed for simplicity. Also, the new TPL API was mostly ignored (just trying to avoid obsolete decorated methods), and a exclusive thread safe method of accessing KVSession was organized.

Please take a look and let me know If anything is off. Gotta make this work.

Thanks a lot

**Comment by dangershony** [comment]
I think this is also related to this PR, seems like the same issue
https://github.com/microsoft/FASTER/pull/226

**Comment by ThiagoT1** [comment]
I just edited to add the exact exception I get, for the tests that write one too many itens.

**Comment by marius-klimantavicius** [comment]
Got a quick look and what happens is that once we hit some threshold (i.e. test case with 227 entries) then the last value overflows segment (which is 8MB for that specific case). After the restart the segment is truncated thus we lose part of the value.

**Comment by badrishc** [comment]
The design of FASTER object log is as follows: for each segment in the main log, there is a corresponding segment of the object log that stores all the corresponding objects from the main log, laid out end to end.

This implies a requirement for the object log: an object log segment needs to grow large enough to accommodate all objects within the corresponding main log segment. The resolution we adopt is for the object log segment to be of _variable size_, i.e., we should not size the object log segment to a specific size a priori. To accomplish this, we need to make sure `preAllocate` is set to `false` for the object log during its `CreateLogDevice' call, because otherwise we would wrongly truncate the segment to the pre-allocate size. As action item, we need this point to be documented and the samples/tests to be updated.

**Comment by badrishc** [comment]
Created PR with fix (see mention above).

**Comment by ThiagoT1** [comment]
Just to add info, changing the preallocateFile parameter makes no difference to the Snapshot tests, while it changes the Snaphot tests.

The Snaphot change is that it can go exactly one entry further before it fails.

![image](https://user-images.githubusercontent.com/16569217/71855509-fbd2bb80-30bf-11ea-86f0-0dd252085e20.png)

@badrishc , does that makes sense?

Thanks a lot for the support.

**Comment by badrishc** [comment]
Yes, I am able to repro this testcase now. We are looking into it.

**Comment by badrishc** [comment]
PR has been updated with a fix, can you verify the same? Thx.

**Comment by ThiagoT1** [comment]
Fixed!

https://github.com/ThiagoT1/FasterDictionary/tree/help-1.0.1-fix

tests passing:

```csharp
        [Theory]
        [InlineData(2833, 1, CheckpointType.FoldOver)]  //OK
        [InlineData(2834, 1, CheckpointType.FoldOver)]  //OK
        [InlineData(50000, 1, CheckpointType.FoldOver)]  //OK
        [InlineData(2832, 1, CheckpointType.Snapshot)] //OK
        [InlineData(50000, 1, CheckpointType.Snapshot)] //OK
```

Also, make some tests with variable key length and preallocateFile: true. Passing.

https://github.com/ThiagoT1/FasterDictionary/tree/help-1.0.2-fix

Thanks a lot!

**Comment by badrishc** [comment]
NuGet with this fix has been pushed out: https://www.nuget.org/packages/Microsoft.FASTER
