### ISSUE TITLE
[C#] Entries Cant Be Recovered After Process Restart (Unsafe Approach)

### ISSUE THREAD

**Issue by ThiagoT1** [microsoft/FASTER#227]
Hi There!

Adding to https://github.com/microsoft/FASTER/issues/225, recover also fails when using a fairly different aproach, giving up serializers and switching to unsafe structs.

There's a threshold (entry count) where recover becomes impossible. It varies with memory / segment / page  sizes.

There's some differences about https://github.com/microsoft/FASTER/issues/225, though:

- Snapshot and Fold Over fail at the same threshold
- Fail does not happen when recovering, instead happening when taking the checkpoint, in the 
form of a CPU core at 100% with the checkpoint not ever completing.

Heres the code that repros:

https://github.com/ThiagoT1/FasterDictionary/tree/unsafe-0.0.1

Tests here:

https://github.com/ThiagoT1/FasterDictionary/blob/07f014edfe5cc8fb887f4518cfa1250b9962107b/tests/FasterDictionary.Tests/Recover/RecoverTests.cs#L37

**Comment by marius-klimantavicius** [comment]
I can reproduce the issue - in essence I get stuck in `PREP_INDEX_CHECKPOINT` (which in my experience is mostly caused by a different session failing to `Refresh`).
I can solve/workaround it by basically replacing `CompleteCheckpointAsync` with `KVSession.CompletePending(true, true);`, but I don't know if it has the same semantics.

I also got (at least once) another hang-style issue (with my changes mentioned above), this time when running `Get`/recovery part of the test, FASTER seems to be stuck in this loop:
``
while ((logicalAddress = hlog.TryAllocate(recordSize)) == 0)
{
    InternalRefresh(ctx);
    Thread.Yield();
}
``
It fails to allocate from hlog because `CannotAllocate` returns true.

**Comment by badrishc** [comment]
Created PR with fix (see mention above).

**Comment by badrishc** [comment]
@ThiagoT1: you no longer need to Ping the dictionary with the new API. The notion of Refresh is not needed, unless you are running in a special mode (`threadAffinitized = true`) that most users will not have to worry about.

**Comment by ThiagoT1** [comment]
@badrishc, the ping is intended to expose the knowledge about the worker queue being empty at the time of completion, provided no other job was queued after that.

**Comment by badrishc** [comment]
Ah ok, thx. With the PR linked above, this (unsafe) issue should be resolved. Can you check?

**Comment by ThiagoT1** [comment]
Will do.

**Comment by ThiagoT1** [comment]
Fixed.

Tests passing: 

https://github.com/ThiagoT1/FasterDictionary/tree/unsafe-0.0.1-fix

```csharp
        [Theory]
        [InlineData(904, 1, CheckpointType.FoldOver)] //OK
        [InlineData(905, 1, CheckpointType.FoldOver)] //OK
        [InlineData(5000, 1, CheckpointType.FoldOver)] //OK
        [InlineData(904, 1, CheckpointType.Snapshot)] //OK
        [InlineData(905, 1, CheckpointType.Snapshot)] //OK
        [InlineData(5000, 1, CheckpointType.Snapshot)] //OK
```

![image](https://user-images.githubusercontent.com/16569217/71866406-b2e12e00-30e4-11ea-8540-9afd1b91f74a.png)

**Comment by badrishc** [comment]
NuGet with this fix has been pushed out: https://www.nuget.org/packages/Microsoft.FASTER
