### ISSUE TITLE
Please Clarify ConcurrentWriter When Using Serializers

### ISSUE THREAD

**Issue by ThiagoT1** [microsoft/FASTER#234]
Hi There!

Variable Length types are our thing.

Do we have to burn resources evaluating serialized sizes? 

I see FasterKV expects ```ConcurrentWriter``` to return true when Values are exactly the same serialized size. Estimating the size is not so cheap when dealing with var length types.

Could you please give us some guidance on how ConcurrentWriter (and InPlaceUpdater) should affect performance when:

- Always returning true;
- Always returning false;
- Costly checking for exactly equal sizes;

Thanks a lot!

**Comment by badrishc** [comment]
If you know that the value being upserted will fit in the space allocated earlier for the same key (if it's a duplicate insert for the same key), then you can always return true.

The return of false is used to catch the case where we cannot do an in place update/upsert because the new value wouldn't fit in the allocated place, so we need to allocate new space in the tail of the log instead.

If you don't expect to get benefit from in place update of the same key, then it's fine to always return false. Every upsert will then be a new entry in the log.

**Comment by marius-klimantavicius** [comment]
I'd add that if you are planning to use varlen iterator, then you should only overwrite value (return true) if the sizes are exactly equal (or at least make sure that `GetLength` returns the same value). 
In my own library I always return `false` (and I have length-prefixed key and value, so it would be cheap to figure out length, but as far as I understood I would have to implement my own locking to prevent multiple threads writing the same location).

**Comment by ThiagoT1** [comment]
> If you know that the value being upserted will fit in the space allocated earlier for the same key (if it's a duplicate insert for the same key), then you can always return true.

"Fit" here means equal or smaller size?

> I'd add that if you are planning to use varlen iterator, then you should only overwrite value (return true) if the sizes are exactly equal (or at least make sure that GetLength returns the same value).

Varlen iterator as when not using serializers?

**Comment by marius-klimantavicius** [comment]
I think I misunderstood what you meant by "Variable Length types". FASTER can operate in 3 "modes" - both key and value are blittable types with fixed size; variable length supported by using `IObjectSerializer` (provided via `SerializerSettings`); and last one is variable length mode in-place by using `IVariableLengthStruct` (variable length but still have to be blittable types). My comment refers to the last mode, I actually don't have too much experience with object serializer.
And by iterator I mean calling `kv.Log.Scan(...)` method and using the returned iterator to enumerate key/values.

**Comment by badrishc** [comment]
Marius has summarized the options well. My answers were also assuming you were using IVariableLengthStruct.

If you are instead using serializers and the separate object log, you can safely always return true for those methods, since the reference pointers to the objects, which are what is stored in the main log, are of course always fixed size.

**Comment by ThiagoT1** [comment]
So, in place updates do not apply to the obj log?

I mean every update to the same key will allocate a new chunk of data, even if the object is on the updatable area?

Thanks a lot for the explanation.

**Comment by badrishc** [comment]
The exact opposite: in-place updates always apply (in the mutable region) since you are always returning true. It's the best we can do. It's identical to a pure in memory data structure, for the mutable region.

**Comment by ThiagoT1** [comment]
Thanks a lot. I'll keep reading docs and code, and trying to contribute.
