### ISSUE TITLE
[C#] FasterLogScanIterator.GetNext should return address of next entry

### ISSUE THREAD

**Issue by mito-csod** [microsoft/FASTER#244]
With the update in 2020.2.1.1, the out long address argument got changed to contain the current address--this renders FasterLogScanIterator.CompleteUntil() unusable, since it expects the "next" address as its argument, but there is no thread-safe way to get this value outside of the previous implementation of out long address. Please consider either reverting the behavior, or adding another out argument for the next address.

Thanks.

**Comment by marius-klimantavicius** [comment]
Checkout `FasterLogScanIterator.NextAddress` field.

**Comment by mito-csod** [comment]
I think that falls in the "not thread safe" category.

Imagine if you have multiple threads calling into GetNext() of a single iterator so that they can do CPU-heavy processing on the data in parallel. Unless you use some synchronization (like a mutex), you have no guarantee that another thread hasn't already called GetNext() in between the time you call your GetNext() and the time you fetch NextAddress. While we certainly *can* do that, I think the most elegant solution would be to return the "would-be-next address" at the call of GetNext() so that we avoid that overhead.

**Comment by badrishc** [comment]
Agreed, this was discussed on Gitter earlier. We need it to be thread-safe, and the call stack is the best way to ensure this.

**Comment by badrishc** [comment]
This requires a bit more clarification. Assume we have two threads calling GetNext simultaneously. A thread calls GetNext, does some processing on the returned item, then calls GetNext again in a loop. Now consider from the perspective of one of these threads.

When it calls GetNext and gets the "next" address (via the proposed fix), the next address represents the address of the entry immediately after the currently returned entry. It does NOT imply that the other concurrent thread has completed processing any previous entry. In other words, FASTER does not know when an iterator thread has finished processing its retrieved entry.

That said, the above proposed extension to get the immediate next address might still be more useful than calling iter.NextAddress - because the former would tell the caller the exact address of the item immediately after the one currently retrieved, whereas the latter might return an address further into the future.
