### ISSUE TITLE
How to ensure memory safety in in-place update?

### ISSUE THREAD

**Issue by yunchih** [microsoft/FASTER#268]
When `logicalAddress >= hlog.ReadOnlyAddress`, we simply RMW by calling `InPlaceUpdater`.
Section 4 of [the paper](https://www.microsoft.com/en-us/research/publication/faster-concurrent-key-value-store-place-updates/) says:

> A thread has guaranteed access to the memory location of a record, as long as it does not refresh its epoch. **This property allows threads to update a value in-place without worrying about memory safety**.

Sec. 2.5:
> A thread calls Acquire to register itself with the epoch mechanism. Next, it issues a sequence of user operations, along with periodic invocations of Refresh (e.g., every 256 operations) to move the thread to current epoch

In other words, even though our value, say, a `struct`, is not `std::atomic`, we can still safely update it in-place.  My question is: how do we keep concurrent reader safe by using epoch?  How does FASTER guarantee a reader won't read a half-updated struct (being updated by concurrent writer)?

I hope this isn't a stupid question 😅

**Comment by badrishc** [comment]
Hi @yunchih , by memory safety we mean that multiple threads can access a region of memory without worrying about it getting reclaimed by the log operations (growth, flush, evict) that happen in parallel. The threads that access the shared memory are still responsible for coordinating their access to it, e..g. in order to prevent broken reads.

For atomics, they can use Interlocked operations such as Interlocked.Increment. For larger structs, they can use record-level locking. One way to perform record-level locking is to have a integer header in your value struct, then use latch-free operations to lock/unlock. Here is a (very rough and untested) example of shared and exclusive latches in C# with several assumptions, to get you on the right track:

```cs        
        public static bool TryAcquireSharedLatch(ref int latch)
        {
            if (latch < 0) return false;
            return Interlocked.Increment(ref latch) > 0;
        }

        public static void ReleaseSharedLatch(ref int latch)
        {
            Interlocked.Decrement(ref latch);
        }

        public static bool TryAcquireExclusiveLatch(ref int latch)
        {
            if (latch == 0)
            {
                return 0 == Interlocked.CompareExchange(ref latch, int.MinValue, 0);
            }
            return false;
        }

        public static void ReleaseExclusiveLatch(ref int latch)
        {
            Interlocked.Exchange(ref latch, 0);
        }
```

**Comment by badrishc** [comment]
For C++, see our tests for examples of larger values. For instance, this one: https://github.com/microsoft/FASTER/blob/d8aaee50487d2cc3aafd837c232fb503ee5c909f/cc/test/in_memory_test.cc#L320

**Comment by yunchih** [comment]
@badrishc Thanks.  That really helps!
