### ISSUE TITLE
What about benchmark comparison also with Caffeine and Cache2k

### ISSUE THREAD

**Issue by wangyjx** [Microsoft/FASTER#27]
There are some another high-performance local cache libraries for Java, like
https://github.com/ben-manes/caffeine
https://cache2k.org/

And their final benchmark https://cruftex.net/2017/09/01/Java-Caching-Benchmarks-Part-3.html?2014-30#Conclusion
 
I am interested in the benchmark comparison between FASTER and those.

**Comment by ben-manes** [comment]
Generally you should take comparative benchmarks with a grain of salt, especially when by the authors as statistics are easy to fudge (e.g. construct it to hide worse cases). Caffeine has very limited posting of its own not because the data wasn't evaluated, but rather it is not the takeaway users should have. Instead users should focus on whether the cache exceeds their performance needs and has the desired capabilities. Once met the authors can use Amdul's law to instead make tradeoffs without impacting real-world performance, such as Caffeine sacrifices maximizing throughput (average latency) for minimizing worst-case latencies. [Collision](https://github.com/comodal/collision) for example is better than both performance-wise, at a reduced hit rate.

I don't think FASTER's goals match those of the Java libraries. FASTER is optimized for write throughput while maintaining consistency with its own persistent storage. This would seem to make it the system-of-record for a key/value database. It has to handle recovery and consistency operations that an application-side cache does not. Because the data is local, the OS page cache is probably quite helpful to make up for deficiencies in LRU (e.g. Linux uses ClockPro) and the miss penalty is low.

Caffeine also uses a log-based write model which allows write throughput to usually be governed by the hash-table. The hash table is updated, an event recorded into a circular buffer, and immediately replayed under a try-lock. An application-side cache needs to support user provided computations to memoize the result (e.g. db lookup), so per-entry locks are required to avoid dogpiling effects. In comparison, FASTER can use a lock-free hash table (think Cliff Click's `NonBlockingHashMap`) as operations are only `get` or `set`. Because there is a high miss penalty, Caffeine does a lot of work to 

I can't speak for cache2k, other than that it uses ClockPro. At least in its original form, that offers high read throughput with low-write throughput by requiring an exclusive lock for updates and worst-case O(n) scans. This would go against FASTER's design goal towards writes, so I think that's further away from being a proper comparison.

I don't think benchmarks are really a good request. FASTER is clearly fast enough. It would be most comparable to `Collision` mentioned above if Java-based, but I think their comparison choices are the most applicable.

**Comment by badrishc** [comment]
We added a wiki post on C# FASTER's performance (https://github.com/Microsoft/FASTER/wiki/Performance-of-FASTER-in-C%23). Our paper has more info as well. Some points I'd add to add:
* C#'s value types (with unsafe access) make it possible (when you write the C# code very carefully) to match C++ performance when your types are blittable value types. We have measured that FASTER C# and C++ have nearly identical performance. To my (limited) knowledge, Java does not have/expose this capability.
* FASTER incurs around 2 cache misses per operation which is the upper bound for throughput performance in such a log setting anyway. CPU is usually not the bottleneck is such benchmarks (num. of cache misses is), although you want to keep CPU usage of the system minimal to leave CPU free for user activity. In this sense, we have carefully tuned FASTER to incur very low CPU in the common case.
* FASTER latencies are pretty low for in-memory data (~100ns - mainly dominated by the cost of the two cache misses)

That said, we don't plan to run more comparisons with existing systems in other languages at this point.
