### ISSUE TITLE
[C#] Proposal: Allow the user to provide function(s) to determine whether entry is alive

### ISSUE THREAD

**Issue by marius-klimantavicius** [microsoft/FASTER#272]
Extend `IFunctions` callbacks `InitialUpdater`, `InPlaceUpdater` and `CopyUpdater` to signal to FASTER that the result of RMW is deletion (set `Tombstone=true`, maybe in addition to making changes).
Alternatively add a new callback that could be used by compactor to determine whether to leave records alive.

Our scenario is that we are considering storing key-values (in our case key is hash and it uniquely identifies value) with refcounts. Some sessions would be upserting to either add new entry with `refcount=1` or increase `refcount`. Other sessions (probably #230 would be nice) would only be decreasing `refcount` and once it reaches `0` the entry should be deleted. Our final goal is that while `refcount>0` the entry can be retrieved and if `recount=0` it will be reclaimed (eventually compacted away).

**Comment by badrishc** [comment]
Here are some thoughts.

This feature gets a bit complicated in the presence of concurrent refcount increments and decrements. Because if an RMW callback tells us to delete, but another thread increments the refcount before FASTER can mark the tombstone, we would be in an inconsistent state (marking a valid record as deleted). One way to solve this is: never let a thread perform in-place update when going from refcount 0 to refcount 1; this has to be done as an RCU. User signals this by the return value of false for `InPlaceUpdater`.

The compactor based solution is also interesting, and possibly superior/less intrusive. Basically, the user provided lambda is used to indicate an "implicit"/logical Tombstone for a record. However, read operations will continue to return the record until it is compacted away, and user has to add logic to treat it as a NOTFOUND.

If `IFunctions` were to add support for this tombsone-checker lambda, then we could post-process reads, but adding an additional function in the read path seems like overkill.

**Comment by marius-klimantavicius** [comment]
It seems that I had some incorrect assumptions when writing this proposal. I assumed that RMW was atomic - all three `InitialUpdater`, `InPlaceUpdater` and `CopyUpdater` were going to be run exclusively. Is it possible to have both `InPlaceUpdater` and `CopyUpdater` running simultaneously?

Currently I am leaning towards customized compaction, will try to experiment with providing custom functions to `Compact` in #270 (maybe even a different interface).

**Comment by badrishc** [comment]
Users manage concurrent access within the function methods. However, the moment control is given back to FASTER by one of these methods, and before FASTER sets the tombstone bit, there is a window of time where another thread can run one of the function methods on the record.

**Comment by badrishc** [comment]
Merged PR, closing issue.
