### ISSUE TITLE
Struggling to get started

### ISSUE THREAD

**Issue by ralphbecket** [microsoft/FASTER#304]
The C# docs are rather thin and all the examples refer to the _FasterKV<Key, Value, Input, Output, Empty, Functions>_ class taking _six_ type parameters.  The current Nuget package only exports a _FasterKV<Key, Value>_ class.  I gather (after much head scratching) that the action doesn't start until you get a _ClientSession_ object on which you can invoke read/write methods that call back into an _IFunctions_ object.  Can I just use _new Functions()_ to get one of these or do I have to implement something different depending on my Key and Value types?

My objective is to store and retrieve objects (I'm happy to turn them into byte arrays or feed them into streams or whatever) indexed by strings.  I see there are some requirements on the Key and Value types to support (de)serialisation, but for the life of me I can't find a loose end of thread I can follow to start unravelling the API.  

Would it be possible to provide a really simple example of how to use Faster to just insert and retrieve, say, string values indexed by string keys?  That would be very much appreciated.

**Comment by badrishc** [comment]
The old FasterKV API used 6 type params, and our docs reflect this. We recently updated the API to introduce a simpler 2-param API, but the documentation does not yet reflect this. The 6-param API is still available and working fine, so the docs are still correct. We will update the docs in the next week or so.

Some other nice end-to-end working examples are in playground:
* Async sample: https://github.com/microsoft/FASTER/blob/master/cs/playground/FasterKVAsyncSample/Program.cs
* Disk read/write with sync and async: https://github.com/microsoft/FASTER/tree/master/cs/playground/FasterKVDiskReadBenchmark/Program.cs
* Simple example with classes instead of structs: https://github.com/microsoft/FASTER/blob/master/cs/playground/ClassSample/Program.cs
* All samples in playground: https://github.com/microsoft/FASTER/tree/master/cs/playground

Below this is a very simple end-to-end example with value types, to get you started. For strings and class types, you need to additionally provide serializers (the example links above will show how).

```cs
        static void Main()
        {
            // Create device where log will spill to disk
            var device = Devices.CreateLogDevice("foo");

            // Create simplest store instance
            using var store
                = new FasterKV<int, int>(
                    1L << 20, // size of hash table in #cache lines; 64 bytes per cache line
                    new LogSettings { LogDevice = device } // log device
                    );

            // Create new "session" to talk to store using default provided callback functions
            using var s = store.NewSession(new SimpleFunctions<int, int>());

            int key = 5, val = 25, inp = 0, outp = 0;

            // Synchronous upsert of value
            s.Upsert(ref key, ref val, Empty.Default, 0);
            
            // Synchronous read of value
            var status = s.Read(ref key, ref inp, ref outp, Empty.Default, 0);
            
            // Check result
            if (status != Status.OK || outp != val)
            {
                throw new NotImplementedException();
            }
        }
```

**Comment by ralphbecket** [comment]
Magic, thank you very much!

**Comment by badrishc** [comment]
Great, you can reach us here or on Gitter chat for more info.
