### ISSUE TITLE
[C#] What to use for CacheValue: struct or class?

### ISSUE THREAD

**Issue by AntyaDev** [microsoft/FASTER#316]
I faced the situation that when I used struct and got session.Read() == PENDING, then even after waiting I wasn't able to read the final value.

Using class seems to resolve this issue.

but then I just wondering when I should use class or struct?

**Comment by badrishc** [comment]
When you use a struct, the async Read result comes to you in the `ReadCompletionCallback` you provide via `IFunctions`. This is because structs are value-types and cannot be updated by async pending callback code.

Blittable structs (https://docs.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types) are much better from FASTER's performance (throughput + memory) perspective. I would try my best to use them. but if you cannot then classes are fine.

**Comment by AntyaDev** [comment]
Thanks a lot.
I just didn't get the idea about ReadCompleationCallback. Now it's clear.

**Comment by AntyaDev** [comment]
Hi @badrishc 

> I would try my best to use them. but if you cannot then classes are fine.

struct Value
{
    public byte[] Content {get;set;}
}

What I can gain if I need to store this struct?
It seems that I can't actually win much here since Content is a reference type, isn't it?
