### ISSUE TITLE
TryAdd equivalent

### ISSUE THREAD

**Issue by aleksey-salow** [microsoft/FASTER#338]
I want implement TryAdd equivalent for Faster. After some research I found several solutions, but need advise about correct and reliable way.

1. Operation status, returned by `Session.RMW()`. If it `NOTFOUND`, raise NewRecord flag. (status is not accessible in RMWAsync)
2. `InitialUpdater` method. If method was called, than we have new record. Return flag via ???
  a. Context. Need to be added to callback functions.
  b. Output parameter, like in Read method. If we read something, we can preprocess and return it.

Custom functions for this task for RMW method:
```
public void InitialUpdater (ref Key key, ref Value input, ref Value value)
{
    value = input ;
}

public void CopyUpdater (ref Key key, ref Value input, ref Value oldValue, ref Value newValue)
{
    newValue = oldValue ;
}

public bool InPlaceUpdater (ref Key key, ref Value input, ref Value value)
{
    return false ;
}
```

Thank you.

**Comment by marius-klimantavicius** [comment]
For your custom functions - `InPlaceUpdater` should return `true`, `false` is used to force a copy of record `CopyUpdater` (mostly useful for variable length structs where new value does not fix the existing record).

What you mean by 'raise NewRecord flag'?

As I understand `Input` is intended to be used as an argument to affect RMW (it does not need to be the same type as `Value`). You could use `Input` to communicate between caller and functions (be careful with value types, if data is loaded from disk you get a copy). Your input could be a `class` containing a `Value` and some kind of status. The status would be set in custom functions - for `InitialUpdater` it would indicate that a new entry was created; `CopyUpdater` and `InPlaceUpdater` would indicate that value already exists.

There is one potential inefficiency with using RMW for this - if `CopyUpdater` is used then a record is duplicated in the log. This could be undesirable, though on the other hand it also acts as a read cache of sorts as it ensures that a record is in memory (that's why it is potential inefficiency).

**Comment by aleksey-salow** [comment]
> What you mean by 'raise NewRecord flag'?

Store it somewhere, so after returning from RMW it can be read. And I'm agree that `Input` can be used for this purpose.

> if `CopyUpdater` is used then a record is duplicated in the log

As I understand it can be avoided by introducing and calling new callback at next locations, before `BlockAllocate`. Making operation cancellable, if creating new record or updating existing is not desired behavior.

https://github.com/microsoft/FASTER/blob/f35a709f94addfd599d19205f05022c3c73493b3/cs/src/core/Index/FASTER/FASTERImpl.cs#L709
https://github.com/microsoft/FASTER/blob/f35a709f94addfd599d19205f05022c3c73493b3/cs/src/core/Index/FASTER/FASTERImpl.cs#L1406

**Comment by badrishc** [comment]
To summarize:

* An RMW return status of `NotFound` implies `InitialUpdater` was called, which implies `TryAdd` succeeded
* An RMW return status of `OK` implies that `TryAdd` failed to add record (it already existed in DB)
* `InPlaceUpdater` should simply return true to indicate that you do not touch the record
* `ReadCopyUpdate` is the suboptimal one. For correctness, just set `newValue` to `oldValue`. We will copy the older record to the tail, but that is a performance inefficiency, not a correctness issue.
* Need to fix `RMWAsync` to return `Status`

**Comment by badrishc** [comment]
A possible breaking change to fix the copy-old-record-to-tail inefficiency is to make `CopyUpdater` return a `bool`. If `false`, then we do not copy to tail, just return a status of `OK` without performing the actual copy to tail of the record.

**Comment by badrishc** [comment]
Updated suggestion above with something that might actually work.

**Comment by aleksey-salow** [comment]
I implemented NoRmwUpdate feature, hope not broke too much. 
https://github.com/aleksey-salow/FASTER/tree/NoRMWUpdate

But still have question about `RMWAsync`. How status can be returned to caller in case of `PENDING` operation?

**Comment by badrishc** [comment]
That modification is on our plate - we will put out a PR when done. In the meanwhile, the workaround would be to either ignore the inefficiency or use a `flag` via `Input` as you discussed earlier.

**Comment by aleksey-salow** [comment]
Ok, thank you. Will wait for new release.

**Comment by badrishc** [comment]
Thanks for the discussion and contribution! We will update once it is ready. 👍

**Comment by badrishc** [comment]
I was thinking, we could **possibly** just add TryAdd and TryAddAsync as first class citizens in FASTER API. Internally, there would be a flag isTryAdd passed in to InternalRMW (internal overload). If flag is set, then we will just use `SingleWriter` to write the value in RMW, instead of calling `InitialUpdater`.

Benefit: the session does not need to dedicate its RMW capability to this.

Downside: is noRmwUpdate via RMW useful for anything other than TryAdd.

Thoughts? How useful or important is TryAdd as a first class functionality to justify this as dedicated API ...

**Comment by marius-klimantavicius** [comment]
Ideally I'd want to be able to conditionally suppress copy from within functions (in similar fashion that we force a copy if `InitialUpdater` returns false). Maybe an additional method (but it should be able to "communicate" with `CopyUpdater`) or an argument that if unused does not create a copy (like lazy-create-entry). 
As for rationale:
I am (was, not sure due to various reasons) considering implementing a `key->set|hash` structure (similar to redis set or even hash). In such scenario I want to be able to prevent a copy if the item being added to a set is already present, otherwise if it is missing then I need to modify the set so a copy is required. While this particular scenario is easy to implement by using prefixed keys, we also have a requirement to be able to enumerate values in the `set|hash`.

**Comment by badrishc** [comment]
We currently first allocate the space for the entry and only then do we call CopyUpdater. Thinking aloud, maybe we have a `ConditionalCopyUpdater` that will have access to a reverse callback like:
```cs
ref Value GetDestinationValueRef()
```
This reverse callback would allocate space and return the ref Value to which `ConditionalCopyUpdater` can write what it wants.

**Comment by badrishc** [comment]
@aleksey-salow: thanks for your sample code. We used the testcase there + implemented a generalized version that will be able to handle `TryAdd` as well as @marius-klimantavicius's use case mentioned [above](https://github.com/microsoft/FASTER/issues/338#issuecomment-699590081) as well, of `key->set|hash`.

PR is linked above.

**Comment by badrishc** [comment]
The PR adds a `NeedCopyUpdate` callback to `IFunctions`, which the application can use to determine if they want to proceed with a log allocation + `CopyUpdater`. The default for this callback is `true`.

In order to force cascading into `NeedCopyUpdate`, `TryAdd` will simply return `false` for `InPlaceUpdater`.

**Comment by badrishc** [comment]
Sample end-to-end working sample use of this linked PR feature to implement `TryAdd` functionality using the in-built `TryAddFunctions`:

```cs
using var store = new FasterKV<long, long>(1L << 20, new LogSettings { LogDevice = new NullDevice() });
using var tryAddSession = store.NewSession(new TryAddFunctions<long, long>());

long key = 3, input1 = 30, input2 = 31, output = 0;

// First TryAdd - success; status should be NOTFOUND (does not already exist)
var status1 = tryAddSession.RMW(ref key, ref input1);

// Second TryAdd - failure; status should be OK (already exists)
var status2 = tryAddSession.RMW(ref key, ref input2);

// Read, result should be input1 (first TryAdd)
var status3 = tryAddSession.Read(ref key, ref output);

if (status1 == Status.NOTFOUND && status2 == Status.OK && status3 == Status.OK && output == input1)
    Console.WriteLine("Success!");
else
    Console.WriteLine("Error!");
```

**Comment by mstaros** [comment]
But if to go this way- what about HasKey functionality? )

**Comment by badrishc** [comment]
What's that, could you expand?

**Comment by mstaros** [comment]
You don't want to read large value into output during this operation. In case of large varlen  for example it could become an issue. Just to get a  boolean instead.

**Comment by badrishc** [comment]
If the record were in the mutable region of log in memory, user can avoid writing out the entire record into `Output` by using `Empty` as `Output` and modifying `ConcurrentReader` to not do anything with the value. This is indeed the reason why we have a separate `Output` type for `Read()`, in addition to the `Value` type.

If the record were instead on disk, then we have to incur one I/O to retrieve the record anyway, and then `SingleReader` will do something similar to `ConcurrentReader` above.

The suboptimality arises if the record were on disk, and larger than one I/O (usually 4K for SSD), or if user were using the object log for class values. In this case, `Read` will unnecessarily bring in the entire value with additional I/Os, only to be dropped after the reader completes its operation.

**Comment by mstaros** [comment]
I see..by why to read the record from the disk at all? Cannot user just  check the hashtable in memory? Or it does not work this way?

**Comment by badrishc** [comment]
The core hash index in memory does not keep the actual keys for memory overhead reasons. It only has hash values, so if a record is not in the memory portion of the record log, then we have to retrieve and check the actual key to ensure that the key matches (as there can be hash collisions).

**Comment by mstaros** [comment]
Yes, sure.  Hash is not enough. But  it all means that if i have short keys and large values and frequent lookups  my best bet is to have a secondary in-memory storage with all these  keys  and empty values?

**Comment by badrishc** [comment]
If you have frequent reads/lookups, then you care about `Value` and the current design is best. But if you have frequent `HasKey` and infrequent lookups, with large values, then an alternate design might be better:

Create a single FasterKV:
* Use small blittable keys (e.g., long, Guid, etc) as `Key`
* Use a long address as `Value`: the address could be an address where only the value is stored, on a separate [FasterLog](https://github.com/microsoft/FASTER/blob/master/docs/cs/FasterLog.md) instance (FasterKV not needed).
* Keep the main FasterKV instance (hash table and its main log) in memory
* A read on main FasterKV serves as a `HasKey` and gives the address of the value on the FasterLog. You can then issue a random read on FasterLog to get the actual value if you need it.

If you don't want the 8-byte address values, you could instead use `Empty` values and a secondary FasterKV, as you pointed out, as well.

**Comment by mstaros** [comment]
Yes, thank you, that what I thought about. Anyway you believe that adding a KeyCache  as a feature to Faster won't help in cases when operations don't care about values -HasKey, TryAdd ?

**Comment by badrishc** [comment]
It's possibly useful, not sure how we would expose it as a first class citizen inside FASTER though. As users can do this from outside even with current FASTER. Contributions welcome.
