### ISSUE TITLE
Loading Large-scale Key-Value Pairs in Benchmarking

### ISSUE THREAD

**Issue by littlepig2013** [Microsoft/FASTER#35]
I tried to use the benchmark code in cc/ to test faster's performance under limited memory but I found that  the function "BlockAllocate" fall into an infinite loop because there's no checkpoint thread when setup the faster key-value store.

I tried to add the checkpoint thread in setup_store function using another checkpoint interval for loading. And this loop will not end until upsert operations are all finished  in thread_setup_store.

After my modification, the setup_store function now can load more key-value pairs even the memory is limited, but another problem comes: after I add checkpoint in setup_store function, the checkpoint thread in run_benchmark can not run normally. What I got is just "Failed to start checkpoint". I checked the comment in "CheckPoint()", which says that there is another checkpoint running. Is there any way I can finish the previous checkpoint thread?

Here is my code in setup_store:

`
while(!load_done_) { 
    if(current_time - last_checkpoint_time >= std::chrono::seconds(1)){
       store->Checkpoint(nullptr, callback, token);
    }
`

The flag `load_done_` will be set true after all upsert operations finished in `thread_setup_store` function.

**Comment by badrishc** [comment]
How did you surmise that the infinite loops is because of no checkpoint thread? FASTER does not need a checkpoint thread to make progress. It does requrer user threads to call Refresh frequently in order to unblock memory so that the tail can move forward in the circular buffer. See the example code in sources for more details on how FASTER is used by threads.

Also, you do not create a separate checkpoint thread. Any FASTER thread can call Checkpoint, if you are indeed looking to create a checkpoint.

If the problem still persists, a stand alone repro would be useful to diagnose further.

**Comment by littlepig2013** [comment]
Thanks a lot! I will see the example codes for more details.
