### ISSUE TITLE
Trying to build a simplified wrapper for a KV store but really don't understand from the docs what's going on.

### ISSUE THREAD

**Issue by keithn** [microsoft/FASTER#391]
So I'm trying to work out if I can use faster as a persisted KV store and trying to write a simple wrapper 

```C#
 class FasterKeyValueStore: IValueStore, IDisposable
    {
        private ClientSession<string, string, string, string, Empty, IFunctions<string, string, string, string, Empty>> _session;
        private FasterKV<string, string> _store;

        public FasterKeyValueStore()
        {
            
            var log =  Devices.CreateLogDevice(@"C:\Temp\hlog.log" );
            var objlog = Devices.CreateLogDevice(@"C:\Temp\hlog.obj.log" );

            var logSettings = new LogSettings {
                LogDevice = log, 
                ObjectLogDevice = objlog,
            };

            _store = new FasterKV<string, string>(
                size: 1L << 20,
                logSettings: logSettings
            );
                       
            _session = _store.NewSession ( new SimpleFunctions<string, string>());
            
        }

        public void Put(string key, string value)
        {
            _session.Upsert(ref key, ref value);
        }

        public string Get(string key)
        {
            var value = "";
            _session.Read(ref key, ref value);
            return value;
        }

        public void Clear()
        {
        }

        public void Dispose()
        {
            _session?.Dispose();
        }
```

then as a simple test...

```C#
            using var fasterStore = new FasterKeyValueStore();
            fasterStore.Put("faster", "test");
            Console.WriteLine(fasterStore.Get("faster"));
```

which shows the right thing.

Then, if I run the program again but  first removing the Put, and just do the get,  the status of the read is NOTFOUND,  which means, it hasn't been stored to disk for whatever reason.   But I can't work out why not ( also I can't see any files )

I can't seem to find any samples that have an example of a super simple KV store similar to this that is persistent across runs.

Maybe I'm missing something? or this library is meant for this?

**Comment by plaisted** [comment]
Data is not guaranteed to be persisted to disk unless you take a snapshot (see https://microsoft.github.io/FASTER/docs/fasterkv-basics/#checkpointing-and-recovery).

The next time you start the program you would need to recover the last snapshot. Last time I used the feature you had to track what snapshot was the latest by Guid but it looks like there may have been some usability improvements (see `Recover()` and `RecoverAsync()` on `IFasterKV` where it appears to grab the latest for you)

**Comment by keithn** [comment]
@plasted
> Data is not guaranteed to be persisted to disk unless you take a checkpoint(see https://microsoft.github.io/FASTER/docs/fasterkv-basics/#checkpointing-and-recovery).
> 

hey, yes, after posting this I found the stuff about taking checkpoints, then found the parts about having to do with compaction.  

I guess what was not clear from the documentation, is out of of the box the library is essentially an in memory kv store that will use disk when it hits its memory limits.

To persist data, in a background thread you take checkpoints at whatever interval seems appropriate then when your process restarts, you need to recover 

The checkpoints will massively grow the log, so you need to go through a compaction cycle where you essentially reinsert stuff into the log then truncate the beginning of the log.

you have to handroll all this micromanaging of the log yourself.  

So, at the moment I'm just trialing this library, and kind of got to the point that I'm not very confident I could configure the system to work well in a production environment without a lot more experimentation.

**Comment by plaisted** [comment]
I'm pretty much in the same boat as you, I keep experimenting with the library every few months for different use cases and decide to use something simpler or that I'm more familiar with as I don't require the concurrency / performance FASTER provides. One thing I will say about it being an in memory KV store with a disk log is that it lets you handle smaller than memory and larger than memory data sets using the same store and get optimal performance for both scenarios. A lot of KV stores with persistence don't give you super low latency for small data sets unless you build your own caching layer as they'll be reading and writing data to disk regardless of total dataset size.

**Comment by badrishc** [comment]
FASTER by default will not automatically take checkpoints, because not all scenarios require checkpoints. This is a library that you can use the way you desire, using the appropriate combination of calls. We have tons of examples [here](https://github.com/microsoft/FASTER/tree/master/cs/samples) to help you, and if you have a new scenario, we will be happy to help here.

> The checkpoints will massively grow the log, so you need to go through a compaction cycle where you essentially reinsert stuff into the log then truncate the beginning of the log.

Checkpoints do not have to grow the log. You can take a snapshot checkpoint, that will not grow the main log at all. Instead it will take a snapshot (photo) of in memory contents to a _separate_ file that you can use to recover later:

```cs
await store.TakeFullCheckpointAsync(CheckpointType.Snapshot);
```

> it looks like there may have been some usability improvements

Correct, during recovery, if you simply call `Recover` without a specific token we will recover to the latest checkpoint.

> you have to handroll all this micromanaging of the log yourself.

In every log-based KV system, if you want to control the expiration of items (instead of letting them expire automatically), you need to invoke compaction (or tune a compaction period). This isn't as complex as you may worry at the beginning. Most typical settings will work swimmingly. You can just take one of our examples and modify it as you see fit. See for instance these samples:
* [StoreLogCompaction](https://github.com/microsoft/FASTER/tree/master/cs/samples/StoreLogCompaction)
* [StoreCheckpointRecover](https://github.com/microsoft/FASTER/tree/master/cs/samples/StoreCheckpointRecover)
* [ClassRecoveryDurability](https://github.com/microsoft/FASTER/tree/master/cs/playground/ClassRecoveryDurability)

> I'm not very confident I could configure the system to work well in a production environment

FASTER is used in production across multiple groups -- I wouldn't worry too much about stability. But yes, there is a learning curve, that is due to our emphasis on being a library that is usable in different scenarios (some of which do not need persistence).

If you have a particular end-to-end sample in mind that could help and is not covered by the above, we will be happy to put it together.

**Comment by keithn** [comment]
Hi Badrish

I've made an example project here https://github.com/keithn/KeyValueTrial  with what I'm trying to do.  Not even really testing, just trying to get something to work where I can run the program, do a bunch of puts into a KV store batched (in a way that it is persisted to disk), then do a bunch of Gets on the KV store.    All the data should be persisted to disk across runs

For comparison is a trivial KV store done with sqlite,  currently, FASTER is not really that different than sqlite when trying to guarantee batched changes are on disk  ( I used the full checkpoint snapshot as suggested).

At the moment, they perform similar on Gets, a bit different on Puts ( but not really sure I'm measuring fasters persistence, it may actually be showing up in the Gets)

now, currently, the checkpoints accumulate, and get bigger and bigger, so from what I'm gathering, what I'd need to do is once I'm sure the checkpoint has been done, I need to go delete any other checkpoint?

my actual use case is an IoT system where there are semi infrequent Puts that can be batched and many high frequency reads.

My problem is I don't think I'm using FASTER efficiently but I don't really know what strategy I should take to make sure I am.

**Comment by mstaros** [comment]
I agree that the log grows way too fast when using fold checkpoint.  Also- how to delete  fold checkpoints preceding to some snapshot ?-some API for that would be helpful.
One more problem- difficulties with resizing. For example, there seems to be  no way to wait for method  growIndex to finish.  Or  may be I am missing somethings.  And should one always make snapshot after resizing of persistent log?

**Comment by badrishc** [comment]
> I've made an example project here https://github.com/keithn/KeyValueTrial with what I'm trying to do. Not even really testing, just trying to get something to work where I can run the program, do a bunch of puts into a KV store batched (in a way that it is persisted to disk), then do a bunch of Gets on the KV store. All the data should be persisted to disk across runs

Your project looks good overall as a starting point. I made two changes:
* Changed number of puts/gets to 100000 so that fixed costs do not dominate.
* For fairness, changed `End()` method of FASTER to below so that it will return only after the checkpoint has completed:
  `_store.TakeFullCheckpointAsync(CheckpointType.Snapshot).GetAwaiter().GetResult();`
* Ran in Release detached mode

Result:
```
Sqlite
Payload size: 25600
Puts Took 12.6249311s
Gets Took 11.5110923s
FASTER
Payload size: 25600
Puts Took 6.000112s
Gets Took 0.0507468s
```

To further optimize FASTER's performance on puts with checkpointing, you can use `Memory<byte>` as key and value types instead of strings, and convert the strings to `Memory<byte>` before inserting into FASTER. This will eliminate the need for a separate object log, and all the data (byte arrays) will be stored in the main log. With this change, the performance is:

```
FASTER
Payload size: 25600
Puts Took 3.7522542s
Gets Took 1.1503234s
```

As you can see, puts are faster, as will be recovery. However, gets take a bit longer because we have to convert the `Memory<byte>` to string on each GET operation, which incurs a temporary byte array allocation as well as string allocation.

Here is my code for `Memory<byte>`:

```cs
    class FasterKeyValueStore : IValueStore, IDisposable
    {
        private ClientSession<Memory<byte>, Memory<byte>, Memory<byte>, (IMemoryOwner<byte>, int), Empty, IFunctions<Memory<byte>, Memory<byte>, Memory<byte>, (IMemoryOwner<byte>, int), Empty>>
            _session;

        private FasterKV<Memory<byte>, Memory<byte>> _store;

        public FasterKeyValueStore()
        {
            var log = Devices.CreateLogDevice(@"hlog.log");
            var objlog = Devices.CreateLogDevice(@"hlog.obj.log");

            var logSettings = new LogSettings
            {
                LogDevice = log,
                ObjectLogDevice = objlog,
            };

            _store = new FasterKV<Memory<byte>, Memory<byte>>(
                size: 1L << 20,
                logSettings: logSettings,
                checkpointSettings: new CheckpointSettings()
                {
                    CheckpointDir = @"." ,
                }
            );

            try
            {
                _store.Recover();
                Console.WriteLine("Recovered");
            }
            catch (Exception e)
            {
                // first recover with no checkpoint spits the dummy
            }

            _session = _store.NewSession(new MemoryFunctions<Memory<byte>, byte, Empty>());
        }

        public void Put(string key, string value)
        {
            var _key = new Memory<byte>(Encoding.ASCII.GetBytes(key));
            var _value = new Memory<byte>(Encoding.ASCII.GetBytes(value));

            _session.Upsert(ref _key, ref _value);
        }

        public string Get(string key)
        {
            var _key = new Memory<byte>(Encoding.ASCII.GetBytes(key));
            (IMemoryOwner<byte>, int) _output = default;
            var status = _session.Read(ref _key, ref _output);
            if(status != Status.OK) Console.WriteLine(status);
            return Encoding.ASCII.GetString(_output.Item1.Memory.Slice(0, _output.Item2).ToArray());
        }

        public void Clear()
        {
        }

        public void Begin()
        {
        }

        public void End()
        {
            _store.TakeFullCheckpointAsync(CheckpointType.Snapshot).GetAwaiter().GetResult();
        }
        


        public void Dispose()
        {
            _session?.Dispose();
        }
    }
```

**Comment by badrishc** [comment]
>now, currently, the checkpoints accumulate, and get bigger and bigger, so from what I'm gathering, what I'd need to do is once I'm sure the checkpoint has been done, I need to go delete any other checkpoint?

Yes, once a "full checkpoint" is completed, you can safely delete all older checkpoints. If your hash index is large, you can also separate out the index and log checkpoints and perform them at difference cadences. See the documentation website for details.

Snapshot takes a full snapshot of the current contents of memory, so yes the snapshots will get bigger as the database gets bigger. If you want incremental checkpoints, use FoldOver checkpoint instead, which will simply flush the latest data in the log to storage.

**Comment by badrishc** [comment]
> My problem is I don't think I'm using FASTER efficiently but I don't really know what strategy I should take to make sure I am.

Your strategy is overall good for a single thread. Note that FASTER scales with the number of threads, so you can use more sessions in parallel to get overall better throughput.

**Comment by badrishc** [comment]
> I agree that the log grows way too fast when using fold checkpoint. Also- how to delete fold checkpoints preceding to some snapshot ?-some API for that would be helpful.

You can just delete older checkpoints whenever the latest has successfully completed. You can implement your own commit manager (extending `DeviceLogCommitCheckpointManager`) that deletes older checkpoints as well. We can eventually add such functionality, but this is not on the short-term roadmap.

> One more problem- difficulties with resizing. For example, there seems to be no way to wait for method growIndex to finish. Or may be I am missing somethings. And should one always make snapshot after resizing of persistent log?

You are right, we need to add an API to complete the index growth, similar to `CompleteCheckpointAsync`. You can configure the index statically if you know the ballpark size a priori. After resizing, you should take a full checkpoint so that you can recover to the newly sized index and log.

**Comment by badrishc** [comment]
Closing for now. As you can see from the above results, there is a huge performance gap between the alternative SQLite and FASTER. The tradeoff is some need for periodic checkpointing and log maintenance (compaction) using the APIs provided by the library. We have plenty of examples to show you how to do this, and we welcome contributions of end-to-end samples as well.

With the planned remote version of FASTER, we might be able to do this log maintenance automatically as we would own the server thread. Thanks for your feedback, and feel free to open new issues if you have other questions.

**Comment by keithn** [comment]
I decided to run with Faster in our production system after your help and rewriting things a bit  to suit our actual usecase.  I think I can get more performance out of it, but mostly just need it to be robust for now, and we are just going through testing,  I think the speed is actually pretty good for 50k+ devices hitting our system in the short term and we can improve later.

**Comment by IbrahimElshafey** [comment]
> In every log-based KV system, if you want to control the expiration of items (instead of letting them expire automatically), you need to invoke compaction (or tune a compaction period). This isn't as complex

Thanks for your comment, It grasps the points not clearly mentioned in the official documentation.
