### ISSUE TITLE
Memory increasing with string type values 

### ISSUE THREAD

**Issue by NachoN** [microsoft/FASTER#54]
I coded some C++ tests based on the sum-store example but modified them a bit to handle string values.

It works great, however the memory consumption gets growing till it eats all my RAM. Using Valgrind and Massif it happens that most of my RmwContexts live forever. Also the async. callbacks (deep copies) used for the contexts are never called.

Best regards & many thanks

**Comment by badrishc** [comment]
RmwContexts are likely not being deleted because the callbacks aren't being called. This means that no I/Os are being completed.

If you are using thread pool I/O (currently supported on Windows, but not Linux) then the question is why the thread pool is not completing the I/Os. (Is Windows just not completing the file reads?) If you are using queue I/O, then you need to explicitly call TryComplete() on the I/O handler.

We may have wrapped TryComplete() inside Refresh(); but that's the most likely explanation. If the sum_store example is insufficient to diagnose, you could try looking at the benchmark driver, as well.

**Comment by NachoN** [comment]
Thanks Badrish.

Tried store.disk.TryComplete() and store.disk.handler().TryComplete() and
still no luck.
I compiled the code for Windows and still see the same issues.

Best regards

**Comment by badrishc** [comment]
Closing as we have not seen this issue in our test cases. Related, @matthewbrookes has a recent PR at https://github.com/microsoft/FASTER/pull/128 that shows how variable length keys may be used with FASTER.
