### ISSUE TITLE
Iterate over the keys written with different `ClientSession<>` instance, in the same file.

### ISSUE THREAD

**Issue by StanislavChankov** [microsoft/FASTER#552]
I am iterating `Iterate()` over the keys , but only keys from the same `ClientSession<>` are being populated.
I want to read/write in/from the same file, which is being closed(process shut down), without being deleted and opened again(Devices.CreateLogDevice).
`recoverDevice: true` does not solve it.

**Expected**:
All Keys/Values are Iterated, regardless of the `ClientSession<>` used to persist them.
**Actual**:
The results I receive are only from the current `ClientSession<>`.

I am interating over the key/values as per documentation:
```
            var dict = new Dictionary<int, RequestLogValue>();
            var scanInterator = requestLog.ClientSession.Iterate();
            while (scanInterator.GetNext(out var recordInfo))
            {
                ref RequestLogKey key = ref scanInterator.GetKey();
                ref RequestLogValue value = ref scanInterator.GetValue();

                dict.Add(key.Key, value);
            }
```

**Comment by badrishc** [comment]
When you are using non-blittable types (e.g., classes or structs with properties), you need to define a serializer for it so that FASTER knows how to read and write the data. See [here](https://microsoft.github.io/FASTER/docs/fasterkv-basics/#constructor-parameters) for details. You need to provide `IObjectSerializer` via KV constructor. An example is here: https://github.com/microsoft/FASTER/blob/master/cs/samples/StoreCustomTypes/Program.cs

**Comment by StanislavChankov** [comment]
Thank you @badrishc . That's what I was thinking is the missing part. Now the values are populated as expected 🚀
