### ISSUE TITLE
Recovery / Allocation error with hybrid log

### ISSUE THREAD

**Issue by koculu** [microsoft/FASTER#672]
I get consistent allocation error in object log when using hybrid log checkpoint.
Recover fails due to this error in Generic Allocator.
I can reproduce the error. Please let me know if you want more details on the issue.

Process terminated. Assertion failed.
   at FASTER.core.GenericAllocator`2.AsyncReadPageWithObjectsCallback[TContext](UInt32 errorCode, UInt32 numBytes, Object context) in D:\code\modern\arge\FASTER-2.0.0-preview.1.2\cs\src\core\Allocator\GenericAllocator.cs:line 629

**Comment by badrishc** [comment]
More details, ideally with a repro, would be great, thanks.

**Comment by koculu** [comment]
Please check your email, I have sent a console app code to reproduce the issue. 3 times the recovery completes with success but the 4th time it crashes.

**Comment by badrishc** [comment]
Also, make sure you are using 64 bit mode in your app as size limits are much lower in 32 bit mode.

**Comment by koculu** [comment]
Thanks for the pointer but the issue is not about memory limits. Allocation issue occurs with 2M strings insert.

**Comment by badrishc** [comment]
This should be fixed with the linked PR. We have merged it to main branch, and also updated the v2 branch. You can use it from sources until the next NuGet release. Note that in the latest v2, there is a breaking change in the IFunctions API: all functions return bool, and `ref RecordInfo` is no longer a part of the parameter list.

**Comment by koculu** [comment]
Thank you very much for awesome and quick fix.
