### ISSUE TITLE
C ABI

### ISSUE THREAD

**Issue by fckt** [Microsoft/FASTER#8]
Is there any plans to add a C ABI? Or I missed it and there is already? Thanks!

**Comment by jahunter-m** [comment]
Not at this time. The C++ FASTER relies on the C++ (pre-)compiler to process templates and generate FASTER code specific to the particular host. So, at this time, the only way to use C/C++ FASTER is to include the C++ header files in your project.

You can create a C ABI in your own project, if you like: you just have to choose how to specialize the C++ FASTER--e.g.:
 1. What sort of values your ABI will store; what sort of keys it will use to retrieve them. (Keys require a hash function, as well.)
 2. How you will read those values from FASTER, atomically and non-atomically.
 3. How you will update those values.
 4. Whether you will store those values on disk, and if so in what format.
 5. Etc.

You can define a general-purpose C ABI; I've done something like that for an earlier project. This gives you flexibility, at the cost of performance, since the FASTER library and the C host can no longer share assumptions about key and value formats, etc.

**Comment by GuacheSuede** [comment]
>The C++ FASTER relies on the C++ (pre-)compiler to process templates and generate FASTER code specific to the particular host

Could you link the line that relates to this ?

Thanks
